github.com:
    users:
        Jash-Dev:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Jash-Dev
